import React from 'react';
import { BrainCircuit, Code2, MessageSquare } from 'lucide-react';

export const TRANSLATIONS = {
  en: {
    appTitle: "Tri-Coder AI",
    subTitle: "Multi-Persona Coding Assistant",
    library: "Library",
    history: "History",
    settings: "Settings",
    newChat: "New Chat",
    newFolder: "New Folder",
    folderName: "Folder Name",
    save: "Save",
    saveToFolder: "Save to Folder",
    exportBackup: "Export Data (JSON)",
    importBackup: "Import Data (JSON)",
    downloadZip: "Download Project (ZIP)",
    inputPlaceholder: "Ask a coding question... (Ctrl+Enter to send)",
    deepThinking: "Deep Thinking",
    deepThinkingOn: "Deep Thinking ON",
    judge: "Judge",
    judgeVerdict: "AI Verdict",
    winner: "Winner",
    waiting: "Waiting...",
    thinking: "Thinking...",
    error: "Error",
    theme: "Theme",
    language: "Language",
    voiceListening: "Listening...",
    fileAttached: "File attached",
    folders: "Folders",
    noHistory: "No history yet",
    preview: "Preview",
    you: "You",
    ai: "Tri-Coder",
    suggestions: "Suggestions",
    copy: "Copy",
    copied: "Copied!",
    download: "Download",
    chatHistory: "Chat History",
    delete: "Delete",
    consensusBtn: "Unify Solutions (Expert Meeting)",
    consensusTitle: "The Master Solution",
    consensusDesc: "Synthesized from all 3 models based on the judge's verdict.",
    retry: "Regenerate",
    aboutApp: "About App",
    reportBug: "Report Bug / Logs",
    reportBugDesc: "Copy system logs to send to developers.",
    copyLogs: "Copy Error Logs",
    noLogs: "No errors recorded yet.",
    tools: {
      debug: "Debug",
      refactor: "Refactor",
      explain: "Explain",
      test: "Unit Test",
      convert: "Convert"
    },
    suggestedPrompts: [
      "Explain logic step-by-step",
      "Optimize this code",
      "Add detailed comments",
      "Write unit tests"
    ],
    help: {
      title: "User Guide",
      modelsTitle: "The Three Personas",
      judgeTitle: "The AI Judge",
      consensusTitle: "Consensus Engine",
      deepThinkingTitle: "Deep Thinking"
    }
  },
  ar: {
    appTitle: "المبرمج الثلاثي",
    subTitle: "مساعد برمجي متعدد الشخصيات",
    library: "المكتبة",
    history: "السجل",
    settings: "الإعدادات",
    newChat: "محادثة جديدة",
    newFolder: "مجلد جديد",
    folderName: "اسم المجلد",
    save: "حفظ",
    saveToFolder: "حفظ في مجلد",
    exportBackup: "تصدير البيانات (JSON)",
    importBackup: "استيراد البيانات (JSON)",
    downloadZip: "تنزيل المشروع (ZIP)",
    inputPlaceholder: "اكتب سؤالك البرمجي... (Ctrl+Enter للإرسال)",
    deepThinking: "تفكير عميق",
    deepThinkingOn: "التفكير العميق مفعل",
    judge: "تحكيم",
    judgeVerdict: "حكم الذكاء الاصطناعي",
    winner: "الفائز",
    waiting: "جاري الانتظار...",
    thinking: "جاري التفكير...",
    error: "خطأ",
    theme: "المظهر",
    language: "اللغة",
    voiceListening: "جاري الاستماع...",
    fileAttached: "تم إرفاق ملف",
    folders: "المجلدات",
    noHistory: "لا يوجد سجل سابق",
    preview: "معاينة",
    you: "أنت",
    ai: "المبرمج الثلاثي",
    suggestions: "اقتراحات",
    copy: "نسخ",
    copied: "تم النسخ!",
    download: "تنزيل",
    chatHistory: "سجل المحادثات",
    delete: "حذف",
    consensusBtn: "توحيد الحلول (اجتماع الخبراء)",
    consensusTitle: "الحل النموذجي الموحد",
    consensusDesc: "تم استخلاصه من النماذج الثلاثة بناءً على توصية التحكيم.",
    retry: "إعادة التوليد",
    aboutApp: "حول التطبيق",
    reportBug: "الإبلاغ عن خطأ / السجلات",
    reportBugDesc: "نسخ سجلات النظام لإرسالها للمطورين.",
    copyLogs: "نسخ سجل الأخطاء",
    noLogs: "لا توجد أخطاء مسجلة حتى الآن.",
    tools: {
      debug: "تصحيح",
      refactor: "تحسين",
      explain: "شرح",
      test: "اختبار",
      convert: "تحويل"
    },
    suggestedPrompts: [
      "اشرح المنطق خطوة بخطوة",
      "حسن أداء الكود",
      "أضف تعليقات توضيحية",
      "اكتب اختبارات للكود"
    ],
    help: {
      title: "دليل المستخدم",
      modelsTitle: "الشخصيات الثلاث",
      judgeTitle: "حكم الذكاء الاصطناعي",
      consensusTitle: "محرك الإجماع",
      deepThinkingTitle: "التفكير العميق"
    }
  }
};

export const AI_MODELS_CONFIG = [
  {
    id: 'deepseek_style',
    name: 'Logic Master',
    shortName: 'Logic',
    sub: 'Architect',
    icon: <BrainCircuit className="w-4 h-4" />,
    baseSystemInstruction: "You are an expert software architect acting as a 'Logic Analyst'. When asked a coding question, DO NOT just write code. First, analyze the problem, explain the algorithm step-by-step, discuss time/space complexity, and then provide the solution.",
    colorClass: 'text-purple-600 bg-purple-50 dark:bg-purple-900/20 border-purple-200 dark:border-purple-800'
  },
  {
    id: 'qwen_style',
    name: 'Code Ninja',
    shortName: 'Code',
    sub: 'Engineer',
    icon: <Code2 className="w-4 h-4" />,
    baseSystemInstruction: "You are a senior backend engineer acting as a 'Code Generator'. Provide highly optimized, production-ready, clean code. Do not provide lengthy explanations. Focus purely on syntax, performance, and best practices.",
    colorClass: 'text-blue-600 bg-blue-50 dark:bg-blue-900/20 border-blue-200 dark:border-blue-800'
  },
  {
    id: 'gemma_style',
    name: 'Mentor',
    shortName: 'Mentor',
    sub: 'Teacher',
    icon: <MessageSquare className="w-4 h-4" />,
    baseSystemInstruction: "You are a friendly coding mentor. Explain concepts simply and clearly. Provide code that is easy to read and well-commented. Balance between explanation and implementation.",
    colorClass: 'text-emerald-600 bg-emerald-50 dark:bg-emerald-900/20 border-emerald-200 dark:border-emerald-800'
  }
];
